export const SET_SELECT_DEPARTMENT_ID = 'SET_SELECT_DEPARTMENT_ID'
export const RESET_DEVICE_CHECK = 'RESET_DEVICE_CHECK'
export const SET_REMARK = 'SET_REMARK'
export const SET_SIGN_IMG = 'SET_SIGN_IMG'
export const RESET_SIGN_IMG = 'RESET_SIGN_IMG'
export const RESET_SELECT_DEPARTMENT = 'RESET_SELECT_DEPARTMENT'

